          
on:
  pull_request:
    types: [closed]

jobs:
 pullrequest:
   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels), 'autorelease')
   runs-on: ubuntu-latest
   steps: 
       - name: print
         run: echo "${{ toJSON(github.event.pull_request.head.ref) }}"
       - name: Initialize Pull Request
         uses: repo-sync/pull-request@v2
         with:
           source_branch: "${{ toJSON(github.event.pull_request.head.ref) }}"
           destination_branch: "main"
           pr_title: "Relase ${{ toJSON(github.event.pull_request.head.ref) }} to main"
           pr_body: ":crown: *An automated PR*"             
           pr_assignee: "bgsandan"                           # Comma-separated list (no spaces)
           pr_label: "auto-pr"                               # Comma-separated list (no spaces)
           pr_allow_empty: true                              # Creates pull request even if there are no changes
           github_token: ${{ secrets.GITHUB_TOKEN }}
