          
on:
  pull_request:
    types: [closed]

jobs:
 pullrequest:
   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
   runs-on: ubuntu-latest
   steps: 
       - name: print
         run: echo "${{ toJSON(github.event) }}"
              echo "${{ toJSON(github.event.sender) }}"
